### ISSUE TITLE
Blocking issues before merging to master.

### ISSUE THREAD

**Issue by glennw** [glennw/webrender#144]
**NOTE:** Not *all* of these need to be blockers - but this is a list of items that I'm aware of which *could* be blockers.
 
 - [x] Some of the newly enabled reftests have introduced more pass / fail differences (transforms, filters) - investigate these.
 - [x] Pixel / texel snapping seems wrong in some cases (maybe only on Linux).
 - [x] Fix image_rendering_auto reftest (should be fixed by above item).
 - [x] Anti aliasing solution.
 - [x] Render target effects + transforms not supported yet.
 - [x] Allow texture cache to clear items.
 - [x] Instancing / GPU clipping.
 - [x] Decompose gradients to rectangles.
 - [x] Support window resizing.
 - [x] Reftests broken by the gradient change: https://github.com/glennw/webrender/issues/167
 - [x] https://github.com/glennw/webrender/issues/168
 - [x] Blend mode issue with text: https://github.com/glennw/webrender/issues/166
 - [x] https://github.com/glennw/webrender/issues/160
 - [x] https://github.com/glennw/webrender/issues/157
 - [x] Box shadow gaps: https://github.com/glennw/webrender/issues/156

Also useful but not blocking:

* Get changes to WPT test scripts etc made to enable different test expectations.
* Integrate with new DL generation code (when it lands).
* Render targets that are scroll roots (probably) not supported yet [not working in normal servo either]
